"""Flask UI for the CTI 05 CICIDS2017 web brute-force benchmark model."""
from __future__ import annotations

from pathlib import Path
from typing import Any

import joblib
import numpy as np
from flask import Flask, jsonify, render_template_string, request


RESULTS_DIR = Path(__file__).parent / "results"
MODEL_DIR = RESULTS_DIR / "models"
DEFAULT_MODEL = "RandomForest"
app = Flask(__name__)
artifact: dict[str, Any] | None = None


def load_artifact() -> None:
    """Load the latest model artifact generated by the real-source pipeline."""
    global artifact
    path = MODEL_DIR / f"{DEFAULT_MODEL}.joblib"
    if path.exists():
        artifact = joblib.load(path)
        print(f"  [OK] Loaded model: {DEFAULT_MODEL}")
    else:
        print(f"  [!] Model not found: {path}")
        print("      Run 'python run.py train' first.")


HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CTI 05 Flow Detector</title><style>
:root{--ink:#e7ecec;--muted:#9fafb2;--bg:#101819;--surface:#182425;--line:#314243;--teal:#4cc7b2;--red:#ff8375;--green:#8de1aa}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.4 Georgia,serif}.wrap{width:min(780px,calc(100% - 30px));margin:34px auto 56px}.eyebrow{font:700 11px/1.2 ui-monospace,Consolas,monospace;letter-spacing:.08em;color:var(--teal);text-transform:uppercase}h1{margin:6px 0;font-size:34px;letter-spacing:0}.intro{color:var(--muted);max-width:650px}.notice{margin:22px 0;padding:13px 15px;border-left:3px solid var(--teal);background:#142120;color:#bdd2d0;font-size:14px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;background:var(--surface);border:1px solid var(--line);padding:18px}label{display:grid;gap:5px;color:var(--muted);font:12px/1.2 ui-monospace,Consolas,monospace}input{width:100%;background:#0f1718;color:var(--ink);border:1px solid var(--line);padding:9px;font:14px ui-monospace,Consolas,monospace}input:focus{outline:2px solid var(--teal);outline-offset:1px}button{margin-top:15px;background:var(--teal);color:#09201c;border:0;padding:11px 18px;font-weight:700;cursor:pointer}button:disabled{opacity:.55}.result{display:none;margin-top:18px;padding:16px;border:1px solid var(--line);background:var(--surface)}.result.show{display:block}.verdict{font:700 22px ui-monospace,Consolas,monospace}.ATTACK{color:var(--red)}.NORMAL{color:var(--green)}.detail{margin-top:6px;color:var(--muted)}.error{color:var(--red);margin-top:14px}@media(max-width:560px){.grid{grid-template-columns:1fr}.wrap{margin-top:22px}}
</style></head><body><main class="wrap"><p class="eyebrow">CTI Lab Exercise 05 / CICIDS2017 benchmark</p><h1>Web Brute-Force Flow Detector</h1><p class="intro">Classify a network-flow record with the same twelve native CICIDS2017 fields used to train the local model.</p><p class="notice">This is a benchmark flow classifier, not a production credential-stuffing verdict. It does not inspect credentials and should be fed telemetry from an authorised network sensor.</p><form id="flow"><div class="grid">
<label>Destination port<input name="destination_port" type="number" value="80" required></label><label>Flow duration<input name="flow_duration" type="number" value="250000" required></label>
<label>Total forward packets<input name="total_fwd_packets" type="number" value="12" required></label><label>Total backward packets<input name="total_backward_packets" type="number" value="4" required></label>
<label>Total forward bytes<input name="total_fwd_bytes" type="number" value="1024" required></label><label>Total backward bytes<input name="total_backward_bytes" type="number" value="512" required></label>
<label>Flow bytes / second<input name="flow_bytes_per_second" type="number" step="any" value="4096" required></label><label>Flow packets / second<input name="flow_packets_per_second" type="number" step="any" value="64" required></label>
<label>SYN flag count<input name="syn_flag_count" type="number" value="1" required></label><label>ACK flag count<input name="ack_flag_count" type="number" value="4" required></label>
<label>Forward IAT mean<input name="fwd_iat_mean" type="number" step="any" value="1000" required></label><label>Backward IAT mean<input name="bwd_iat_mean" type="number" step="any" value="1200" required></label>
</div><button id="submit" type="submit">Classify flow</button></form><div id="error" class="error"></div><section id="result" class="result"><div id="verdict" class="verdict"></div><p id="detail" class="detail"></p></section></main><script>
const form=document.getElementById('flow');form.addEventListener('submit',async(event)=>{event.preventDefault();const button=document.getElementById('submit');const error=document.getElementById('error');const result=document.getElementById('result');button.disabled=true;error.textContent='';result.classList.remove('show');const payload=Object.fromEntries(new FormData(form).entries());Object.keys(payload).forEach(key=>payload[key]=Number(payload[key]));try{const response=await fetch('/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Classification failed');const verdict=document.getElementById('verdict');verdict.textContent=data.verdict;verdict.className='verdict '+data.verdict;document.getElementById('detail').textContent='Model: '+data.model+' | probability of web brute-force: '+data.attack_probability.toFixed(3);result.classList.add('show')}catch(exception){error.textContent=exception.message}finally{button.disabled=false}});
</script></body></html>"""


def extract_features(data: dict[str, Any], features: list[str]) -> np.ndarray:
    """Validate a request against the model's exact native feature contract."""
    try:
        values = [float(data[name]) for name in features]
    except (KeyError, TypeError, ValueError) as error:
        raise ValueError(f"A numeric value is required for every flow feature: {', '.join(features)}") from error
    vector = np.array([values], dtype=np.float64)
    if not np.isfinite(vector).all():
        raise ValueError("Flow feature values must be finite numbers.")
    return vector


@app.route("/")
def index() -> str:
    """Render the local benchmark classification form."""
    return render_template_string(HTML)


@app.route("/predict", methods=["POST"])
def predict() -> tuple[Any, int] | Any:
    """Classify one network flow against the retrained model artifact."""
    if artifact is None:
        load_artifact()
    if artifact is None:
        return jsonify({"error": "No trained model found. Run 'python run.py train' first."}), 500
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        return jsonify({"error": "A JSON object with flow features is required."}), 400
    features = artifact.get("features", [])
    try:
        vector = extract_features(data, features)
    except ValueError as error:
        return jsonify({"error": str(error)}), 400
    scaler = artifact.get("scaler")
    if scaler is not None:
        vector = scaler.transform(vector)
    model = artifact["model"]
    prediction = int(model.predict(vector)[0])
    probability = float(model.predict_proba(vector)[0][1]) if hasattr(model, "predict_proba") else float(prediction)
    return jsonify({
        "anomaly": bool(prediction),
        "verdict": "ATTACK" if prediction else "NORMAL",
        "attack_probability": probability,
        "model": DEFAULT_MODEL,
    })


if __name__ == "__main__":
    print("  CTI 05 CICIDS2017 Flow Detector -- Web UI")
    load_artifact()
    print("  Open http://127.0.0.1:5006")
    app.run(debug=True, host="127.0.0.1", port=5006)
